export enum AppPermission {
    // --- Church Management ---
    CHURCH_MANAGE = 'CHURCH_MANAGE', // Edit church details, settings
    CHURCH_VIEW = 'CHURCH_VIEW', // View detailed stats

    // --- Members ---
    MEMBER_VIEW = 'MEMBER_VIEW',
    MEMBER_CREATE = 'MEMBER_CREATE',
    MEMBER_UPDATE = 'MEMBER_UPDATE',
    MEMBER_DELETE = 'MEMBER_DELETE',
    MEMBER_EXPORT = 'MEMBER_EXPORT',

    // --- Counseling ---
    COUNSELING_CREATE = 'COUNSELING_CREATE',
    COUNSELING_VIEW_OWN = 'COUNSELING_VIEW_OWN',
    COUNSELING_VIEW_ALL = 'COUNSELING_VIEW_ALL',
    COUNSELING_VIEW_SENSITIVE = 'COUNSELING_VIEW_SENSITIVE', // View private notes in shared cases
    COUNSELING_VIEW_SUPERVISION = 'COUNSELING_VIEW_SUPERVISION', // Supervision role for Pastors
    COUNSELING_UPDATE = 'COUNSELING_UPDATE',
    COUNSELING_DELETE = 'COUNSELING_DELETE',

    // --- Groups ---
    GROUP_CREATE = 'GROUP_CREATE',
    GROUP_UPDATE = 'GROUP_UPDATE',
    GROUP_DELETE = 'GROUP_DELETE',
    GROUP_VIEW = 'GROUP_VIEW',
    GROUP_MANAGE_MEMBERS = 'GROUP_MANAGE_MEMBERS',

    // --- Families ---
    FAMILY_CREATE = 'FAMILY_CREATE',
    FAMILY_UPDATE = 'FAMILY_UPDATE',
    FAMILY_DELETE = 'FAMILY_DELETE',
    FAMILY_VIEW = 'FAMILY_VIEW',

    // --- Ministry ---
    MINISTRY_VIEW = 'MINISTRY_VIEW',
    MINISTRY_MANAGE = 'MINISTRY_MANAGE',
    MINISTRY_EVENT_MANAGE = 'MINISTRY_EVENT_MANAGE',

    // --- Library ---
    LIBRARY_VIEW = 'LIBRARY_VIEW',
    LIBRARY_MANAGE_BOOKS = 'LIBRARY_MANAGE_BOOKS',
    LIBRARY_MANAGE_LOANS = 'LIBRARY_MANAGE_LOANS',

    // --- Prayers ---
    PRAYER_VIEW_ALL = 'PRAYER_VIEW_ALL', // View public/leaders requests
    PRAYER_CREATE = 'PRAYER_CREATE',
    PRAYER_MANAGE = 'PRAYER_MANAGE', // Update/Delete any request

    // --- Treasury/Finance ---
    FINANCE_VIEW = 'FINANCE_VIEW',
    FINANCE_MANAGE = 'FINANCE_MANAGE', // Create transactions, budgets
    FINANCE_AUDIT = 'FINANCE_AUDIT', // View audit logs

    // --- Users & Roles ---
    ROLE_MANAGE = 'ROLE_MANAGE', // Assign roles to others

    // --- Agenda ---
    AGENDA_CREATE_CHURCH = 'AGENDA_CREATE_CHURCH',
    AGENDA_CREATE_MINISTRY = 'AGENDA_CREATE_MINISTRY',
}
